lib/Layout/profil.dart
Fixes #5
Layout Profil sudah (dzikri riandri)
=> Profil | Layout

lib/Layout/DashboardPage.dart, lib/Layout/ProfilPage.dart, pubspec.lock, pubspec.yaml
=> Membuat Layout Dashboard | Hisbulloh

lib/Class/TokoClass.dart, lib/ClassService.dart/TokoService.dart, lib/Layout/TokoList.dart, lib/Proses/CekProfil.dart, lib/main.dart
=> Testing Fetch Data Toko  | Afif

lib/Layout/TransaksiPage.dart, lib/main.dart
Fixes #7
Riky Dimas Dermawan telah menyelesaikan layout transaksi
=> Transaksi | Layout

lib/Layout/MenuLayout.dart, pubspec.lock
=> Menu | Layout

lib/Class/MemberClass.dart, lib/ClassService.dart/MemberClassService.dart
=> MemberClass | Objek & Method

lib/ClassService.dart/MemberClassService.dart
=> MemberClassService

lib/Class/DonasiClass.dart
Fixes #17
donasi class Dzikri Riandri
=> DonasiClass | Objek & Method

lib/ClassService.dart/DonasiService.dart
Fixes #47
Donasi Service Dzikri riandri
=> DonasiService

lib/Layout/BarangList.dart
=> Barang | Layout

lib/Class/BarangClass.dart
Fixes #12
Riky Dimas Sudah Menyelesaikan
=> BarangClass | Objek & Method

lib/ClassService.dart/BarangService.dart
Fixes #52
Riky Dimas Telah Menyelesaikan BarangService
=> BarangService | Controler

lib/Class/BarangClass.dart, lib/ClassService.dart/BarangService.dart, lib/Layout/BarangList.dart, lib/Layout/HomeScreen.dart, lib/Layout/MenuLayout.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
=> Proses Tambah Data | CRUD Barang

lib/ClassService.dart/BarangService.dart, lib/Layout/BarangList.dart
Fixes #60
Menambah proses update dan hapus data barang | Afif W
=> Proses Update & Hapus Data | CRUD Barang

android/app/build.gradle, lib/Class/TokoClass.dart, lib/Layout/FormInfoPage.dart, lib/Layout/HomeScreen.dart, lib/Layout/LoginPage.dart, lib/Layout/MenuLayout.dart, lib/Layout/Registerpage.dart, lib/Layout/TokoList.dart, lib/Proses/CekProfil.dart, lib/main.dart, pubspec.lock, pubspec.yaml
Fixes #62
Membuat Layout Lengkapi Info
=> FormInfoToko | Layout

lib/Class/LaporanPemasukanClass.dart, lib/ClassService.dart/LaporanPemasukanService.dart
=> LaporanPemasukanClass & Service

lib/Class/LaporanPemasukanClass.dart, lib/Class/LaporanPenjualanClass.dart, lib/ClassService.dart/LaporanPenjualanService.dart, pubspec.lock
=> LaporanClass | Objek & Method | Afif

lib/ClassService.dart/TokoService.dart, lib/Layout/BarangList.dart, lib/Layout/HomeScreen.dart, lib/Layout/Pageview.dart, lib/main.dart
=> PageViewDashboard

lib/Layout/DashboardPage.dart
=> LayoutDashboardUpdate

lib/Layout/MenuLayout.dart, lib/Layout/PenyaluranDonasi.dart
=> Form Penyaluran Donasi

lib/Layout/Memberlayout.dart
=> Member | Layout

lib/Class/DonasiClass.dart, lib/ClassService.dart/DonasiService.dart, lib/Layout/DonasiData.dart, lib/Layout/MenuLayout.dart
=> Donasi Data | Layout

lib/Layout/Donasilayout.dart
=> Donasi Crud | Proses

lib/Class/TokoClass.dart, lib/Layout/HomeScreen.dart, lib/Layout/ProfilPage.dart, lib/Layout/TokoList.dart
=> Merapikan Halman Profil

lib/Class/MemberClass.dart, lib/ClassService.dart/MemberService.dart, lib/Layout/Memberlayout.dart
Fixes #103
Riky Dimas Sudah Menyelesaikan
=> Member | CRUD | Layout | Service

lib/Class/DonasiClass.dart, lib/Class/LaporanPemasukanClass.dart, lib/Class/TokoClass.dart, lib/ClassService.dart/TokoService.dart, lib/Layout/DashboardPage.dart, lib/Layout/Donasilayout.dart, lib/Layout/HomeScreen.dart, lib/Layout/LaporanLayout.dart, lib/Layout/MenuLayout.dart, lib/Layout/Supplier/BeliBarangSupplier.dart, lib/Layout/TransaksiPage.dart, lib/main.dart
=> Laporan | Layout

lib/Layout/PenyaluranDonasi.dart
=> Data Penyaluran Donasi | Layout

lib/ClassService.dart/PenyaluranDonasiService.dart, lib/Layout/MenuLayout.dart, lib/Layout/PenyaluranDonasi.dart, lib/Layout/PenyaluranDonasiData.dart
Bagus Done
Perbaikan PenyaluranDonasi
Fixes #110
=> Bagus Done

lib/Layout/LaporanLayout.dart, lib/Layout/MenuLayout.dart
=> Memperbaiki Laporan | Layout

lib/Class/TokoClass.dart, lib/Layout/DashboardPage.dart, lib/Layout/HomeScreen.dart, lib/Layout/LaporanLayout.dart, lib/Layout/LoginPage.dart, lib/Layout/Memberlayout.dart, lib/Layout/Supplier/BeliBarangSupplier.dart, lib/Layout/TransaksiPage.dart, lib/main.dart
=> Memperbaiki Bug & menambah diskon member
